#!/usr/bin/env python3

import load_data as LD 

if __name__ == '__main__':
    LD.load_MI()
    LD.load_MN()
    LD.load_MO()
    LD.load_MS()
    LD.load_MT()
    LD.load_NC()
    LD.load_ND()
    LD.load_NE()
    LD.load_NH()
    LD.load_NJ()
    LD.load_NM()
    LD.load_NV()
    LD.load_NY()
    LD.load_OH()
    LD.load_OK()
    LD.load_OR()
    LD.load_PA()
    LD.load_RI()
    LD.load_SC()
    LD.load_SD()
    LD.load_TN()
    LD.load_TX()
    LD.load_UT()
    LD.load_VA()
    LD.load_VT()
    LD.load_WA()
    LD.load_WI()
    LD.load_WV()
    LD.load_WY()